### ISSUE TITLE
Create package website with usethis and pkgdown

### ISSUE THREAD

**Issue by drmowinckels** [martigso/stortingscrape#4]
What a great package!

Just wanted to tip you off that with just a couple extra steps, your package documentation can be created and served via github pages. 
There are some great utility functions to set that up in the usethis package.

https://usethis.r-lib.org/reference/use_pkgdown.html

My experience is that a lot of people discover and explore R packages by these websites, so its a nice extra exposure :)

**Comment by martigso** [comment]
Thanks for the suggestion. Will fix as soon as I can find the time.
